name: Triggered Workflow
on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Trigger Message
        run: echo "Workflow triggered from another repository!"
