name: Receive repository dispatch event

on:
  repository_dispatch:
    types: [dispatch-event]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Event received
        run: echo "Event received"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout the correct branch
        run: git checkout ${{ github.event.client_payload.branch }}

      - name: Verify Current Branch
        run: git branch --show-current

      - name: Verify Branch
        run: echo "Workflow running on branch ${{ github.event.client_payload.branch }}"
