name: Receive repository dispatch event

on:
  repository_dispatch:
    types: [dispatch-event]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Event received
        run: echo "Event received"

      - name: Checkout the specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: Echo Test
        run: echo "Hello, world!"
      
